# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Slovenia Ruby User Group
description:      A Ruby User Group for developers in Slovenia and nearby
url:              http://rug.si/
encoding:         utf-8
github:
  repo:           https://github.com/SloveniaRUG/SloveniaRUG.github.io
meetup:
  url:            http://www.meetup.com/Ruby-Slovenia/

author:
  name:           Miha Rekar
  url:            https://mr.si/

paginate:         5

gems:
- jekyll-mentions
- jemoji
